version: '3.4'
services:
  httpd:
    image: nginx:1.19-alpine
    depends_on:
      - php-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "92:80"

  php-fpm:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "192:80"

  mysql:
    image: mariadb:10.5.8
    volumes:
      - recr7daysTask2Db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "database"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3116:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.8
    environment:
      - PMA_HOST=mysql
    ports:
      - "93:80"

volumes:
  recr7daysTask2Db:
